# configuration for labeler workflow, see https://github.com/actions/labeler

documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/*'

plugin:
- changed-files:
  - any-glob-to-any-file: 'plugins/*'
